version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.0.1
workflows:
  node-tests:
    jobs:
      - node/test:
          run-command: lint
      - node/test
      - node/test:
          setup:
              - browser-tools/install-chrome
          run-command: e2e
