version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.0.1
jobs:
  build:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
workflows:
  node-tests:
    jobs:
      - node/test:
          name: test-lint
          run-command: ci-lint
      - node/test:
          name: test-unit
          setup:
              - browser-tools/install-chrome
          run-command: ci-test
      - node/test:
          name: test-e2e
          setup:
              - browser-tools/install-chrome
          run-command: cie2e
      - build:
          name: build
          requires:
            - test-lint
            - test-unit
            - test-e2e


