version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.0.1
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
  test:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/install-packages
      - browser-tools/install-chrome
      - run:
          command: npm run ci-test
      - coveralls/upload
workflows:
  node-tests:
    jobs:
      - node/test:
          name: test-lint
          run-command: ci-lint
          version: '12.16.1'
      - test:
          name: test-unit
      - node/test:
          name: test-e2e
          setup:
              - browser-tools/install-chrome
          run-command: ci-e2e
          version: '12.16.1'
      - build:
          name: build
          requires:
            - test-lint
            - test-unit
            - test-e2e


